apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-production.yml -o ops/kubernetes/
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: cache
  name: cache
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cache
    spec:
      containers:
      - command:
        - memcached
        - -m 64
        image: memcached
        name: cache
        ports:
        - containerPort: 11211
        resources: {}
      restartPolicy: Always
status: {}
